CREATE PROCEDURE [dbo].[FI_SP_IncBeneficiario]
    @CPF VARCHAR(11), @Nome VARCHAR(100), @IdCliente BIGINT
AS
BEGIN
    INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE) VALUES (@CPF, @Nome, @IdCliente)
    SELECT SCOPE_IDENTITY() AS ID
END
GO