CREATE PROCEDURE [dbo].[FI_SP_AltBeneficiario]
    @Id BIGINT, @CPF VARCHAR(11), @Nome VARCHAR(100), @IdCliente BIGINT
AS
BEGIN
    UPDATE BENEFICIARIOS SET CPF = @CPF, NOME = @Nome, IDCLIENTE = @IdCliente WHERE ID = @Id
END
GO