CREATE PROCEDURE [dbo].[FI_SP_VerificaBeneficiario]
    @CPF VARCHAR(11), @IdCliente BIGINT, @IdBeneficiario BIGINT = NULL
AS
BEGIN
    IF @IdBeneficiario IS NULL
        SELECT ID, CPF, NOME, IDCLIENTE FROM BENEFICIARIOS WHERE CPF = @CPF AND IDCLIENTE = @IdCliente
    ELSE
        SELECT ID, CPF, NOME, IDCLIENTE FROM BENEFICIARIOS WHERE CPF = @CPF AND IDCLIENTE = @IdCliente AND ID <> @IdBeneficiario
END
GO